<div class="alert alert-block alert-success">
    <h1 align="center">Scikit-Learn Tips</h1>
    <h3 align="center">Tip 15 : Drop - Onehotencoding</h3>
</div>

Use drop='if_binary' with OneHotEncoder to drop the first category ONLY if it's a binary feature (meaning it has exactly two categories).

See example 👇

In [1]:
import pandas as pd
X = pd.DataFrame({'Shape':['circle', 'oval', 'square', 'square'],
                  'Color': ['pink', 'yellow', 'pink', 'yellow'],
                   'Sex' : ['man' , 'woman' , 'man' , 'woman']})

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
# Shape has 3 categories, Color has 2 categories
X

Shape   Color    Sex
0  circle    pink    man
1    oval  yellow  woman
2  square    pink    man
3  square  yellow  woman

In [14]:
# drop=None (default) creates one feature column per category
ohe = OneHotEncoder()
#ohe.fit_transform(X[['Sex']].reshape(-1, 1))


In [4]:
# drop=None (default) creates one feature column per category
ohe = OneHotEncoder(sparse=False, drop=None)
ohe.fit_transform(X)

array([[1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.]])

In [5]:
# drop='first' drops the first category in each feature
ohe = OneHotEncoder(sparse=False, drop='first')
ohe.fit_transform(X)

array([[0., 0., 0.],
       [1., 0., 1.],
       [0., 1., 0.],
       [0., 1., 1.]])

In [6]:
# drop='if_binary' drops the first category of binary features
ohe = OneHotEncoder(sparse=False, drop='if_binary')
ohe.fit_transform(X)

array([[1., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 1.]])